Fixing http request time out avoiding region failover for high latency request
Azure/azure-cosmosdb-java pull request #360
Opened 2020-09-11 19:24 UTC by simplynaveen20

Currently we have an api on ConnectionPolicy setRequestTimeoutInMillis which sets the request time out for both TCP and HTTP requests.
We want to cap the lower value of http client request time out to 60 sec, as http network request call ends up into region fail over and also Gateway does not have any sla.

This PR also contains the improvement on AddressResolutionStatistics in ClientSideRequestStatistics, which include error message if there is any failure on address cache refresh call, also including flag inflightRequest which will indicate whether address call finished in lifetime of the the request.

2020-09-11 19:33 UTC, simplynaveen20 commented on sdk/src/test/java/com/microsoft/azure/cosmosdb/rx/internal/HttpRequestTimeoutTest.java
> +			// TODO https://github.com/Azure/azure-cosmosdb-java/issues/359
Should we including this fix too , making query plan read call ? Its just a small change and possibly no impact , but I am little hesitant touching anything out of current issue context

2020-09-14 18:34 UTC, moderakh approved these changes
please fix the minor comments. other than that LGTM.

2020-09-14 18:34 UTC, moderakh commented on sdk/src/test/java/com/microsoft/azure/cosmosdb/rx/internal/HttpRequestTimeoutTest.java
> +	public void DocumentWrite() {
```suggestion
	public void documentWrite() {
```

2020-09-14 18:34 UTC, moderakh commented on sdk/src/test/java/com/microsoft/azure/cosmosdb/rx/internal/HttpRequestTimeoutTest.java
> +	public void DocumentRead() {
please fix the method names as per Java code style.

2020-09-14 18:34 UTC, moderakh commented on sdk/src/test/java/com/microsoft/azure/cosmosdb/rx/internal/HttpRequestTimeoutTest.java
> +	public void DocumentQuery() {
ditto

2020-09-14 18:34 UTC, moderakh commented on sdk/src/test/java/com/microsoft/azure/cosmosdb/rx/internal/directconnectivity/ClientSideRequestStatisticsTest.java
> +	public void AddressResolutionStatistics() {
method name, fix as per java method naming.

2020-09-14 18:54 UTC, moderakh commented on commons/src/main/java/com/microsoft/azure/cosmosdb/ClientSideRequestStatistics.java
> +        private boolean inflightRequest = true;
could you please add a comment what this is?

2020-09-14 19:10 UTC, kushagraThapar requested changes

2020-09-14 19:10 UTC, kushagraThapar commented on sdk/src/test/java/com/microsoft/azure/cosmosdb/rx/internal/HttpRequestTimeoutTest.java
> +			// TODO https://github.com/Azure/azure-cosmosdb-java/issues/359
Good point, I think we can include this because the impact of query plan not being retried on Gateway failed request will be the same. 
We can create a separate PR for this fix, so to run separate CI on just this change, but I think we should fix it as part of the release.

2020-09-14 19:10 UTC, kushagraThapar commented on commons/src/main/java/com/microsoft/azure/cosmosdb/ClientSideRequestStatistics.java
> +        private boolean inflightRequest = true;
Why do we need this if we can verify this behavior through `endTime` ?
As I recall, if the address resolution is in process, then `endTime` has a value of max time, no ?

On a side note, I think we should initialize `endTime` with null, until we hit `addressResolutionEnd`, thoughts ?

2020-09-14 20:36 UTC, simplynaveen20 commented on sdk/src/test/java/com/microsoft/azure/cosmosdb/rx/internal/HttpRequestTimeoutTest.java
> +			// TODO https://github.com/Azure/azure-cosmosdb-java/issues/359
I included in this PR itself,scope is overlapping , as Sams club fail over did happen because of query

2020-09-14 20:40 UTC, simplynaveen20 commented on commons/src/main/java/com/microsoft/azure/cosmosdb/ClientSideRequestStatistics.java
> +        private boolean inflightRequest = true;
This is normal our code flow that if one replica gives error we start address refresh in parallel  while talking to other replica, please check code [here](https://github.com/Azure/azure-cosmosdb-java/blob/ca1307963ba53ce4d1aa7bb21447f06c75f10a76/direct-impl/src/main/java/com/microsoft/azure/cosmosdb/internal/directconnectivity/StoreReader.java#L296)
So there were several incidences in logs where address call stared but the request got completed before that.
This will give clear information that request is inflight

2020-09-14 20:42 UTC, simplynaveen20 commented on commons/src/main/java/com/microsoft/azure/cosmosdb/ClientSideRequestStatistics.java
> +        private boolean inflightRequest = true;
EndTime initialization to null should be fine. Changed it
On InflightRequest, this is normal code flow that if one replica gives error we start address refresh in parallel while talking to other replica, please check code [here](https://github.com/Azure/azure-cosmosdb-java/blob/ca1307963ba53ce4d1aa7bb21447f06c75f10a76/direct-impl/src/main/java/com/microsoft/azure/cosmosdb/internal/directconnectivity/StoreReader.java#L296)
So there were several incidences in logs where address call stared but the request got completed before that.
This will give clear information that request is inflight

2020-09-14 20:51 UTC, simplynaveen20 commented on commons/src/main/java/com/microsoft/azure/cosmosdb/ClientSideRequestStatistics.java
> +        private boolean inflightRequest = true;
Added comment

2020-09-14 21:41 UTC, kushagraThapar commented on commons/src/main/java/com/microsoft/azure/cosmosdb/ClientSideRequestStatistics.java
> +        private boolean inflightRequest = true;
Good point. Thanks.

2020-09-14 21:41 UTC, kushagraThapar commented on sdk/src/test/java/com/microsoft/azure/cosmosdb/rx/internal/HttpRequestTimeoutTest.java
> +			// TODO https://github.com/Azure/azure-cosmosdb-java/issues/359
Thanks @simplynaveen20

2020-09-14 21:42 UTC, kushagraThapar approved these changes
LGTM

2020-09-14 22:50 UTC, mbhaskar approved these changes
Left minor comment regarding license. Please take a look. Thanks for including the QueryPlan change.

2020-09-14 22:50 UTC, mbhaskar commented on commons/src/main/java/com/microsoft/azure/cosmosdb/ClientSideRequestStatistics.java
> +        resolutionStatistics.endTime = null;
Thanks for this change. It was misleading something to see weird max time.

2020-09-14 22:50 UTC, mbhaskar commented on sdk/src/test/java/com/microsoft/azure/cosmosdb/rx/internal/HttpRequestTimeoutTest.java
> +/*
Please change to Microsoft licence

2020-09-14 23:21 UTC, simplynaveen20 commented on sdk/src/test/java/com/microsoft/azure/cosmosdb/rx/internal/HttpRequestTimeoutTest.java
> +/*
done

2020-09-15 02:41 UTC, merged